### ISSUE TITLE
Usage in Angular 2 RC6

### ISSUE THREAD

**Issue by RaphaelHippe** [kahlil/oddstream#1]
Hey, 
I want use unidirectional dataflow in my APP using oddstream. 
However when I try using it I am getting this error message: 

`Error: No provider for OddStream!`

I tried adding it to the providers Array of the NgModule but that didn't help. 
Any idea what else I have to do?

Thanks & Cheers
Raphael Hippe

**Comment by kahlil** [comment]
I have not tried it with ngmodules yet and i am not sure what i have to change. 

But you can just import the package make an OddStream instance and use the api without all the dependeny injection stuff i think. 
I will make sure to look into making it work better with ngmodules later on.

**Comment by RaphaelHippe** [comment]
Seems to work!
Thanks :)

**Comment by kahlil** [comment]
haha nice 💯
